name: jupyter-earth

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - seaborn
  - retrolab
  - ipywidgets
  - jupyter-book
  - cython
  - fortran-magic
  - jupyterlab-geojson
  - ipyleaflet
  - leafmap
  - pip
  - pip:
    - sphinxcontrib-bibtex<2.0.0
