name: jupyter-earth

channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - seaborn
  - retrolab
  - ipywidgets
  - cython
  - fortran-magic
  - jupyterlab-geojson
  - ipyleaflet
  - leafmap
  - pip
  - pip:
    - jupyter-book
    - sphinxcontrib-bibtex
