name: build-docs

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/build-image.yaml
      - hub.jupytearth.org-image/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/workflows/build-image.yaml
      - hub.jupytearth.org-image/**

jobs:
  build-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: conda-forge
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python --version
        conda env create -f docs/environment.yml

    - name: Build book
      run: |
        source activate jupyter-earth
        jupyter-book build ./docs

    - name: Deploy to gh-pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        cname: jupytearth.org
